// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GraphQL: typeof import('./src/components/GraphQL.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    SampleStore: typeof import('./src/components/SampleStore.vue')['default']
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
  }
}

export { }
