// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CatsListing: typeof import('./src/components/listings/catsListing.vue')['default']
    CollectionItem: typeof import('./src/components/molecules/collectionItem.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    FilterToolbar: typeof import('./src/components/toolbars/filterToolbar.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    FormSelect: typeof import('./src/components/formSelect.vue')['default']
    FormText: typeof import('./src/components/formText.vue')['default']
    GraphQL: typeof import('./src/components/GraphQL.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Item: typeof import('./src/components/molecules/item.vue')['default']
    ItemCatCollection: typeof import('./src/components/molecules/itemCatCollection.vue')['default']
    ItemCatHeading: typeof import('./src/components/molecules/itemCatHeading.vue')['default']
    ItemForm: typeof import('./src/components/forms/itemForm.vue')['default']
    ItemsListing: typeof import('./src/components/listings/itemsListing.vue')['default']
    LoginForm: typeof import('./src/components/forms/loginForm.vue')['default']
    LoginToolbar: typeof import('./src/components/toolbars/loginToolbar.vue')['default']
    ModalAccount: typeof import('./src/components/modalAccount.vue')['default']
    ModalConfirm: typeof import('./src/components/modalConfirm.vue')['default']
    ModalForm: typeof import('./src/components/modalForm.vue')['default']
    PrtFormField: typeof import('./src/components/PrtFormField.vue')['default']
    PrtFormFieldArea: typeof import('./src/components/PrtFormFieldArea.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    RegisterForm: typeof import('./src/components/forms/registerForm.vue')['default']
    SampleStore: typeof import('./src/components/SampleStore.vue')['default']
    SearchBox: typeof import('./src/components/molecules/searchBox.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SidebarHeading: typeof import('./src/components/molecules/sidebarHeading.vue')['default']
    SidebarItem: typeof import('./src/components/molecules/sidebarItem.vue')['default']
    SortBox: typeof import('./src/components/molecules/sortBox.vue')['default']
    Tags: typeof import('./src/components/molecules/tags.vue')['default']
    TagsListing: typeof import('./src/components/listings/tagsListing.vue')['default']
    TaxForm: typeof import('./src/components/forms/taxForm.vue')['default']
  }
}

export { }
